### ISSUE TITLE
Feat(naive-ui)：naive-ui组件导入可以选择按需导入

### ISSUE THREAD

**Issue by little1d** [aehyok/video2blog#1]
![image](https://github.com/aehyok/video2blog/assets/115958756/2a5fb6b8-8f35-4673-8ff4-3ff9ae36fd91)
我注意到您`main.ts`中`naive-ui`使用的是全局安装
使用`npm i`在安装项目依赖的时候，需要的时间太久了，后续本地打开localhost的时间肯定也会受影响（本人之前踩过坑）
建议使用`naive-ui`按需导入方法，加上`unplugin-auto-import `插件来实现自动导入

可以参考链接：https://www.naiveui.com/zh-CN/os-theme/docs/import-on-demand

**Comment by fucheng830** [comment]
很赞的建议

**Comment by aehyok** [comment]
@little1d @fucheng830 已经改成按需导入了
