### ISSUE TITLE
[BUG] 使用git-lfs下载出现配额受限

### ISSUE THREAD

**Issue by little1d** [aehyok/video2blog#2]
![1ae40a406ef6cb3abde3dc499692040](https://github.com/aehyok/video2blog/assets/115958756/03c10cb5-984f-42df-bdca-28ce38ae15d5)
clone仓库时，由于仓库lfs带宽和存储空间限制，lfs跟踪记录的*.exe文件无法被正常克隆

正常情况下，~/command/win下面应该有三个文件
![image](https://github.com/aehyok/video2blog/assets/115958756/0e9818b2-5614-40a5-aea2-b44e8e4f2751)

如果你想了解lfs带宽或存储空间详情，可以参考https://docs.github.com/zh/billing/managing-billing-for-git-large-file-storage/viewing-your-git-large-file-storage-usage

**Comment by little1d** [comment]
目前暂且考虑将这三个文件使用google云盘的方式存储，用户自行下载并粘贴到对应文件夹下
mac文件夹下内容：https://drive.google.com/drive/folders/1n4bbRp27sM7g9_D0XrRFqW2OLVNeXONv?usp=sharing
win文件夹下内容：https://drive.google.com/drive/folders/1s8ZYxqaSox-fLHjQQF0tUr7ogMCTM5-S?usp=drive_link

**Comment by aehyok** [comment]
@little1d 已移除git-lfs，并将可执行文件的下载地址写在readme，下载地址也就是上面的，后期文件如果有修改，下载地址会有变动，最终以readme中的为主

**Comment by aehyok** [comment]
@little1d 已移除git-lfs，并将可执行文件的下载地址写在readme，下载地址也就是上面的，后期文件如果有修改，下载地址会有变动，最终以readme中的为主
